author: Lancern

keywords: Hexo, Theme-AD

description: Lancern's Blog

# 导航栏头部名称
nav_name: Lancern's Blog

# 导航栏座右铭
motto: 消灭C++暴政，世界属于Rust！

github: "https://github.com/Lancern/"

# 站点图标和APP图标
favicon:
  icon: /images/favicon.ico
  touch_icon: /images/touch-icon.png

# RSS文件位置
rss:

# 自定义样式文件
custom_styles:

# 自定义脚本文件
custom_scripts:

# 代码高亮主题: normal | night | night blue | night bright | night eighties
highlight_theme: "normal"

# 开启数学公式渲染
mathjax: true

copyright:
  enable: true
  author: "Lancern"
  show_link: true
  more: 'Copyright (c) Lancern, 2019.'

# 建站时间. 格式：YYYY-MM-DD
start_time: "2019-12-10"

# 如何开启 评论&统计 插件：https://godbmw.com/passages/2018-11-15-theme-bmw-docs-zh/
# 请申请自己的 appid 和 appkey，并且替换下面的 appid 和 appkey
leancloud:
  appid: Hyq9wkH495DgNHWhDQCOfQSp-gzGzoHsz # 填写您的appid
  appkey: WaR7nrzhliHj9aVwdQzkdlGd # 填写您的appkey
  comment: false # 是否开启评论系统
  count: false # 是否开启文章统计

# 需要保证leancloud.count为true
welcome:
  enable: false
  interval: 30

# 需要保证leancloud.comment为false
disqus:
  enable: false
  id:

# 需要保证leancloud.count为false
busuanzi: false

# 存放sha256加密的密码
# 拥有所有加锁文章的阅读权限
passwords: []

share:
  twitter: true
  facebook: true
  weibo: true
  qq: true
  wechat: true

analytics:
  baidu:
    enable: false
  google:
    enable: false
    id:
  "360":
    enable: false
    id:

# 打赏图片
reward: []

# 第三方库的CDN地址
# 请根据情况自行决定是否替换为国内CDN
cdn:
  leancloud: "//cdn.jsdelivr.net/npm/leancloud-storage@3.11.1/dist/av-min.js"
  mathjax: "//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"
  valine: "//unpkg.com/valine/dist/Valine.min.js"
  busuanzi: "//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"
  font_awesome: "//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"

nav:
  -
    name: "Home"
    path: "/"
  -
    name: "Archives"
    path: "/archives/"
  -
    name: "Tags"
    path: "/tags/"
  -
    name: "Categories"
    path: "/categories/"
  # -
  #   name: "Friends"
  #   path: "/friends/"
  # -
  #   name: "About"
  #   path: "/about/"

footer: []
footer_contact: "Email: msrlancern@126.com"

friends_avatar_cdn:
friends: []
